### ISSUE TITLE
Clarification on api-audiences

### ISSUE THREAD

**Issue by likku123** [chaospuppy/irsa-demo#1]
Hi @chaospuppy 
I really appreciate your contribution around IRSA for RKE2. Thank you ! very much.

I am following your steps for my test and one thing where I was stuck is here

https://github.com/chaospuppy/irsa-demo/blob/main/ansible/roles/oidc/templates/kube-apiserver.yaml.j2#L3C19-L3C28

api-audiences=irsa.demo,https://kubernetes.default.svc.cluster.local,rke2

I have configure OIDC provider in AWS and the audience I mention is sts.amazonaws.com . Do you thing I need to specify the same in api-audiences and also can you please explain why you have specified irsa.demo in your example.

Thank you!

**Comment by chaospuppy** [comment]
Hi @likku123, you're very welcome!  I'm glad you found it useful. 

It's been a while since I looked at this repo, so my answer here will be a little dusty.  The short answer is because [this document](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#audiences) for the pod-identity-webhook told me to (not specifically `irsa.demo`).

The longer answer is that value could be anything as long as the [`--token-audience`](https://github.com/chaospuppy/irsa-demo/blob/a01a982826761f71298b8e13f36a9e62d253d1f6/k8s/apps/pod-identity-webhook/deployment.yaml#L26) and the [`aws_iam_openid_connect_provider`](https://github.com/chaospuppy/irsa-demo/blob/a01a982826761f71298b8e13f36a9e62d253d1f6/terraform/identity-provider/variables.tf#L9) resource agree on the value.  Lastly,
> the API server requires that any projected tokens used for pod to API server authentication must have this audience set

so that's where it comes in for the `--api-audience` flag.

Finally to your question about `sts.amazonaws.com`, that's the default value for the AWS Identity Provider because typically an AWS Identity Provider would expect the client looking to validate a token to be STS.  You could totally keep that default value and change `irsa.demo` to `sts.amazonaws.com` if you wanted, and it should work.

**Comment by likku123** [comment]
Thank you @chaospuppy for the detail explanation. Basically I am planning to implement it for RKE2 and you setup was super helpful.
